%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB (R2024a) and Database Toolbox Version 24.1 on 11-Dec-2024 12:02:26
clc;clear;close all;
r = 45.72;
% Make connection to database
conn = mysql('Cascading Delay','root','pixhawk2');

%Set query to execute on the database
query = [sprintf('SELECT * FROM cas_delay_test.aircraft WHERE ev_radius = %f',r )];

% Execute query and fetch results
data = fetch(conn,query);
save('aircraft.mat', 'data')
% data = sqlread(conn,'aircraft');

% Close connection to database
close(conn)

% Clear variables
clear conn; clear query;